import 'package:shahi_catalogue/models/product_detail_model.dart';

class ProductDetailProvider {
  // static final List<ProductDetail> mouthFreshenersDetail = [
  //   ProductDetail(
  //       1,
  //       11,
  //       'Refreshing Minty chocolate Pan Masala. A blend of chocolate covered Fennel, Coconut, Sesame Seeds and Betel Nuts.',
  //       'Fennel, Coconut, Linseed, Sesame, Sugar, Supari, Cocoa Powder, N.N.Sweetener (0.3%), Artificial Flavors, Food Colour',
  //       'assets/images/nutrition_facts/aas_pas_cpm_nf.jpg'),
  //   ProductDetail(
  //       2,
  //       12,
  //       'Refreshing Metha Pan Masala. A blend of Fennel, Dry dates, Betel Nut, Cardamom, Menthol, N.N.Sweetener Natural and Artificial Flavours. The ingredients releases flavors that are refreshing to the mouth',
  //       'Coconut, Funnel Seed, Coriander seed, Sesame seed, Sugar, Menthol, Betel Nut, Wheat Flour, Food Colours (E-171) ,(E-102) ,(E-110) ,(E-133) ,(E-127), Flavours (Natural & Artificial)',
  //       'assets/images/nutrition_facts/aas_pas_mpm_nf.jpg'),
  //   ProductDetail(
  //       3,
  //       13,
  //       'A childhood classic, Sugar coated fennel seeds with a burst of color & sweetness.',
  //       'Fennel, Sugar, Flavours, Wheat Flour, Colors: Titanium Dioxide (E-171) ,FD&C Yellow # 5 (E-102) ,FD&C Red 40 (E-129) ,FD&C Blue 1 (E-133)',
  //       'assets/images/nutrition_facts/aas_pas_ss_nf.jpg'),
  //   ProductDetail(
  //       4,
  //       14,
  //       'Herbal mouth freshener with a blend of Malethi, Catechu & Menthol with Dry Dates,  Fennel Seeds & Sugar.',
  //       'Dry Dates, Fennel, Cardamom, Catechu, Malethi, Menthol, Flavours & N.N Sweetener',
  //       'assets/images/nutrition_facts/hittt_nf.jpg'),
  //   ProductDetail(
  //       5,
  //       15,
  //       'The original, Shahi Classic is the original Shahi Supari with the perfect combination of Fennel Seeds, Betel Nuts, Cardamom Seeds and Flavours.',
  //       'Fennel seed, Areca nut, Natural and Artificial Flavour, Menthol and N.N.Sweetener',
  //       'assets/images/nutrition_facts/shahi_classic_nf.jpg'),
  //   ProductDetail(
  //       6,
  //       16,
  //       'Shahi Deluxe is a blend of Fennel Seeds, Dry Dates Cardamom Seeds, and Betel Nuts. Shahi Deluxe provides its users a safe and effective substitute to Pan and Cigarettes.',
  //       'Fennel, Dry dates, Betel nut, Cardamom, Menthol, N.N.Sweetener Natural and Artificial Flavours',
  //       'assets/images/nutrition_facts/shahi_deluxe_nf.jpg'),
  //   ProductDetail(
  //       7,
  //       17,
  //       'The same great taste that consumers have come to love with Shahi Deluxe but without betel nuts. A mouth freshener that can be enjoyed by kids & adults alike.',
  //       'Fennel Seeds, Dry Dates, Cardamom, Menthol, Natural & Artificial Flavours & N.N.Sweetener',
  //       'assets/images/nutrition_facts/shahi_deluxe_lite_nf.jpg'),
  //   ProductDetail(
  //       8,
  //       18,
  //       'Shahi Elaichi provides a cool burst of freshness for the senses achieved through the powerful combination of Fennel Seeds, Betel Nuts and Whole Cardamom.',
  //       'Fennel, Cardamom, Betel Nut, Dry dates, Menthol, N.N.Sweetener and Flavours',
  //       'assets/images/nutrition_facts/shahi_elaichi_nf.jpg'),
  //   ProductDetail(
  //       9,
  //       19,
  //       'Shahi Meva is the ultimate combination of Sweet Fennel, Healthy Almonds, Mouth Watering Chocolate and Vanilla covered Coconut, Crunchy Sugar Crystals and Chewy Dry Dates.',
  //       'Almond, Dry dates, Coconut, Fennel, Flavours, Sugar',
  //       'assets/images/nutrition_facts/shahi_meva_nf.jpg'),
  //   ProductDetail(
  //       10,
  //       20,
  //       'A strong, minty blend of Fennel Seeds, Dry Dates and Betel Nuts with flavours that provide a burst of freshness in your mouth.',
  //       'Fennel Seeds, Dry Dates and Betel Nuts, Menthol, N.N.Sweetener Natural and Artificial Flavours',
  //       'assets/images/nutrition_facts/shahi_super_mint_nf.jpg'),
  // ];

  static final List<ProductDetail> ballayBallayDetail = [
    ProductDetail(
        1,
        11,
        'Fried Chana Dal coated with a unique blend of spices and flavours.',
        'Yellow Peas, Vegetable Oil_(Palmolein), Citric Acid (E-330), Salt,_Red Chilli, Carom Seeds, Cumin,_Maltodextrin, & Nature Identical Flavours.',
        'Pois Jaunes, Huile Végétale (palmoléine), acide citrique _(E-330), sel, piment rouge, graines de carambole, cumin,_Maltodextrine et arômes identiques à la nature.',
        '',
        'assets/images/products/ballay_ballay/nutrition/nutrition1.png'),
    ProductDetail(
        2,
        12,
        'Dal moong: crunchy, crispy fried moong dal with salt & seasoning.',
        'Moong Dal, Vegetable Oil_(Palmolein) & Salt.',
        'Moong Dal, huile végétale_(Palmoléine) & Sel.',
        '',
        'assets/images/products/ballay_ballay/nutrition/nutrition2.png'),
    ProductDetail(
        3,
        13,
        'A spicy and savory blend of Sev and Masoor Dal.',
        'Pea Flour, Rice  Flour, Lentils, Salt, Red Chilli, Cumin,_Carom Seeds, Vegetable Oil, Citric Acid (E-330),_Maltodextrin, Fumaric Acid (E-297) & Nature_Identical Flavours.',
        'Pea Flour, Rice  Flour, Lentils, Salt, Red Chilli, Cumin, Carom Seeds,_Vegetable Oil, Citric Acid (E-330), Maltodextrin, Fumaric Acid_(E-297) & Nature Identical Flavours.',
        '',
        'assets/images/products/ballay_ballay/nutrition/nutrition3.png'),
    ProductDetail(
        4,
        14,
        'A unique blend of Sev, Peanut, Masoor Dal, Chana and Potato sticks coated with a sweet and savory blend of flavours.',
        'Potatoes, Pea Flour, Gram Flour, Rice Flour,_Lentils, Peanuts, Vegetable Oil, Salt, Citric Acid_(E330), Red Chilli, Black Pepper, Sugar, Maltodextrin,_Dextrose & Nature Identical Flavours.',
        'Pommes de terre, farine de pois, farine de gramme, farine de riz,_Lentilles, cacahuètes, huile végétale, sel, acide citrique_(E330), piment rouge, poivre noir, sucre, maltodextrine,_Dextrose & Saveurs identiques à la nature.',
        '',
        'assets/images/products/ballay_ballay/nutrition/nutrition4.png'),
    ProductDetail(
        5,
        15,
        'Namak Paray: crispy fried dough wafer flavored with cumin and carom seeds',
        'Flour, Salt, Cumin, Thyme &_Refined Vegetable Oil.',
        'Farine, Sel, Cumin, Thym &_Huile végétale raffinée.',
        '',
        'assets/images/products/ballay_ballay/nutrition/nutrition5.png'),
    ProductDetail(
        6,
        16,
        'Crispy fried peanuts sprinkled with salt.',
        'Peanuts, Vegetable Oil (Palmolein)_& Salt',
        'Cacahuètes, huile végétale (palmoléine) et sel',
        '',
        'assets/images/products/ballay_ballay/nutrition/nutrition6.png'),
    ProductDetail(
        7,
        17,
        'A savory combination of Sev, Matar, Papdi and Peanuts.',
        'Gram Flour, Rice Flour, Pea Flour, Lentils, Peanuts, Peas,_Vegetable Oil (Palmolein), Salt, Fumaric Acid (E-297),_Carom Seeds, Cumin,  Sugar, Red Chilli, Maltodextrin,_Corriander, Citric Acid (E-330), Permitted Food_Colors(E-124, E-102, E-133) & Nature Identical Flavours.',
        'Farine de Gram, Farine de Riz, Farine de Pois, Lentilles, Cacahuètes, Pois,_Huile Végétale (Palmoléine), Sel, Acide Fumarique (E-297),_Graines de carambole, cumin, sucre, piment rouge, maltodextrine,_Corriandre, acide citrique (E-330), aliment autorisé_Couleurs (E-124, E-102, E-133) et saveurs identiques à la nature.',
        '',
        'assets/images/products/ballay_ballay/nutrition/nutrition7.png'),
  ];

  static final List<ProductDetail> shahiNimcoDetail = [
    ProductDetail(
        1,
        21,
        'Golden Fried Potato sticks covered with a black pepper seasoning.',
        'Potatoes, Vegetable Oil (Palmolein), Salt, Black _Pepper, Cumin, Coriander, Maltodextrin, Citric Acid _(E-330), Sugar and Nature Identical Flavor.',
        'Pommes de terre, huile végétale (palmoléine), sel, poivre _noir, cumin, coriandre, maltodextrine, acide citrique _(E-330), sucre et arôme identique à la nature.',
        'assets/images/products/shahi_nimco/arabic/arabic1.png',
        'assets/images/products/shahi_nimco/nutrition/nutrition1.png'),
    ProductDetail(
        2,
        22,
        'Traditional fried dough ballsperfect as a snack or for adding to yogurt.',
        'Gram Flour, Vegetable Oil (Palmolein) & Salt.',
        'Farine de gramme, huile végétale (palmoléine) et sel.',
        'assets/images/products/shahi_nimco/arabic/arabic2.png',
        'assets/images/products/shahi_nimco/nutrition/nutrition2.png'),
    ProductDetail(
        3,
        23,
        'A classic combination of sweet and savory to satisfy all your cravings. ',
        'Rice Flakes, Gram Flour, Peanuts, Raisins, _Fennel Seed, Turmeric, Vegetable Oil (Palmolein), _Salt, Sugar, Red Chilli, Citric Acid (E-330).',
        'Flocons de riz, farine de pois chiches, cacahuètes, _raisins secs, Graines de fenouil, curcuma, huile végétale _(palmoléine), sel, sucre, piment rouge, acide citrique (E-330).',
        'assets/images/products/shahi_nimco/arabic/arabic3.png',
        'assets/images/products/shahi_nimco/nutrition/nutrition3.png'),
    ProductDetail(
        4,
        24,
        'Golden Fried Potato stickscovered with a spicy red pepper seasoning.',
        'Potatoes, Vegetable Oil (Palmolein), _Citric Acid (E-330), Salt, Red Chilli, Black _Pepper, Carom Seeds, Cumin, Mando Powder, _Nature Identical Flavor.',
        'Pommes de terre, huile végétale (palmoléine), _Acide citrique (E-330), sel, piment rouge, poivre _noir, graines de carambole, cumin, poudre de _mando, arôme identique à la nature.',
        'assets/images/products/shahi_nimco/arabic/arabic4.png',
        'assets/images/products/shahi_nimco/nutrition/nutrition4.png'),
    ProductDetail(
        5,
        25,
        'Crisp fried Yellow Chickpea Lentils covered with a spicy and savory flavor blend',
        'Potatoes, Vegetable Oil (Palmolein), Salt, Black _Pepper, Cumin, Coriander, Maltodextrin, Citric Acid _(E-330), Sugar and Nature Identical Flavor.',
        'Pommes de terre, huile végétale (palmoléine), sel, poivre _noir, cumin, coriandre, maltodextrine, acide citrique _(E-330), sucre et arôme identique à la nature.',
        'assets/images/products/shahi_nimco/arabic/arabic5.png',
        'assets/images/products/shahi_nimco/nutrition/nutrition5.png'),
    ProductDetail(
        6,
        26,
        'Fried and Salted Yellow Moong Lentils',
        'Moong Daal, Vegetable Oil (Palmolein) & Salt.',
        'Moong Daal, huile végétale (palmoléine) et sel.',
        'assets/images/products/shahi_nimco/arabic/arabic6.png',
        'assets/images/products/shahi_nimco/nutrition/nutrition6.png'),
    ProductDetail(
        7,
        27,
        'Spicy and Savory combination of Fried Dough Noodles and Red lentils.',
        'Gram Flour, Rice Flour, Peas Flour, _Lentils, Vegetable Oil (Pamolein), _Salt, Citric Acid, (E-330), Red Chilli _Cumin, Carom Seeds, Maltodextrin & _Nature Identical Flavor.',
        'Farine de pois chiches, farine de riz, farine de pois, _lentilles, huile végétale (pamoléine), sel, acide _citrique (E-330), piment rouge, cumin, graines de _carambole, maltodextrine et arôme identique à la _nature.',
        'assets/images/products/shahi_nimco/arabic/arabic7.png',
        'assets/images/products/shahi_nimco/nutrition/nutrition7.png'),
    ProductDetail(
        8,
        28,
        'A unique blend of sev (thin dough noodles), Peanut, Channa Dal, Channa (Chickpeas) & Potato Sticks coated with a sweet & savory blend of flavours..',
        'Potatoes, Gram Flour, Rice Flour, Lentils, Peanuts, _Vegetable Oil (Palmolein), Salt,  Black Pepper, _Red Chilli, Sugar, Citric Acid (E-330), Mix Spices, _Maltodextrin, Dextrose & Natural Identical Flavours.',
        'Pommes de terre, farine de pois chiches, farine de riz, _lentilles, cacahuètes, Huile Végétale (Palmoléine), Sel, Poivre _Noir, Piment rouge, sucre, acide citrique (E-330), mélange _d\'épices, Maltodextrine, Dextrose & Arômes Identiques _Naturels.',
        'assets/images/products/shahi_nimco/arabic/arabic8.png',
        'assets/images/products/shahi_nimco/nutrition/nutrition8.png'),
    ProductDetail(
        9,
        29,
        'Crispy Fried dough perfect as a topping or a snack!',
        'Wheat Flour, Vegetable Oil, (Palmolein) _Carom Seeds, Cumin & Salt.',
        'Farine de blé, huile végétale, (palmoléine) _Graines de carambole, cumin et sel.',
        'assets/images/products/shahi_nimco/arabic/arabic9.png',
        'assets/images/products/shahi_nimco/nutrition/nutrition9.png'),
    ProductDetail(
        10,
        30,
        '---------------------------------------------',
        'Lentils and Pulses, Vegetable Oil (Palmolein), Raisins, _Peanuts, Chickpea flour, Potato, Salt, Carom Seeds, _Cumin, Asafoetida, Black Pepper, Citric Acid (E330) and _Nature Identical Flavor.',
        'Lentilles et légumes secs, huile végétale (palmoléine), raisins secs, arachides, _farine de pois chiche, pomme de terre, sel, graines de carambole, cumin, _asafoetida, poivre noir, acide citrique (E330) et saveur identique de la nature.',
        'assets/images/products/shahi_nimco/arabic/arabic10.png',
        'assets/images/products/shahi_nimco/nutrition/nutrition10.png'),
    ProductDetail(
        11,
        31,
        'Golden Fried Potato sticks with a hint of salt.',
        'Potatoes, Vegetable Oil (Palmolein), Salt, _Sugar, Maltodextrin.',
        'Pommes de terre, huile végétale (palmoléine), _sel, sucre, maltodextrine.',
        'assets/images/products/shahi_nimco/arabic/arabic11.png',
        'assets/images/products/shahi_nimco/nutrition/nutrition12.png'),
    ProductDetail(
        12,
        32,
        'A savory and spicy blend of Gram Flour Dough Noodles, Fried Lentils and Peas, Shahi Savory Mix is sure to give your taste buds a tantalizing experience.',
        'Gram Flour, Rice Flour, Pea Flour, Lentils and Pulses, Peanut, _Chickpeas, Vegetable Oil (Palmolein), Citric Acid (E-330), _Coriander, Cumin, Red Chilli, Sugar, Carom Seed, Salt, _Maltodextrin, Nature Identical Flavor.',
        'Farine de pois chiches, farine de riz, farine de pois, lentilles _et légumineuses, arachide, pois chiches, huile végétale _(palmoléine), acide citrique (E-330), coriandre, cumin, _piment rouge, sucre, graines de carambole, sel, _maltodextrine, arôme identique à la nature .',
        'assets/images/products/shahi_nimco/arabic/arabic12.png',
        'assets/images/products/shahi_nimco/nutrition/nutrition12.png'),
  ];

  static final List<ProductDetail> snacksDetail = [
    ProductDetail(
        1,
        41,
        'Crispy Corn Sticks covered with a copious amount of flavours. Available in Spicy Masala and Cheese. Kin Korn is sure to satisfy your hunger',
        'Corn Meal, Vegetable Oil (Palmolein), Salt, Whey Powder, _Maltodextrin, Garlic Powder, Onion Powder, Dextrose, _Permitted Food Color Sunset Yellow (E110) and Nature_Identical Flavor (Cheese).',
        'Farine de maïs, huile végétale (palmoléine), sel, poudre _de lactosérum, maltodextrine, poudre d\'ail, poudre _d\'oignon, dextrose, colorant alimentaire autorisé jaune _orangé (E110) et arôme identique à la nature (fromage).',
        '',
        'assets/images/products/snacks/nutrition/nutrition1.png'),
    ProductDetail(
      2,
      42,
      'Crispy Corn Sticks covered with a copious amount of flavours. Available in Spicy Masala and Cheese. Kin Korn is sure to satisfy your hunger.',
      'Corn Meal, Vegetable Oil (Palmolein), Salt, Citric Acid _(E330), Carom Seed, Coriander, Red Chilli, Sugar, _Maltodextrin, Permitted Food Color (E124) and Nature _Identical Flavor.)',
      'Farine de maïs, huile végétale (palmoléine), sel, acide _citrique (E330), graines de carambole, coriandre, piment _rouge, sucre, maltodextrine, colorant alimentaire _autorisé (E124) et arôme identique à la nature.',
      '',
      '', /*'assets/images/products/snacks/nutrition/nutrition2.png'*/
    ),
    ProductDetail(
        3,
        43,
        'Refreshing Minty chocolate Pan Masala. A blend of chocolate covered Fennel, Coconut, Sesame Seeds and Betel Nuts.',
        'Corn Meal, Salt, Vegetable oil, Cumin, Red chilli, _Carom Seeds, Sugar, Nature Identical Flavours, _Citric Acid (E330), Maltodextrin & Dextrose.',
        'semoule de maïs, sel, huile végétale, cumin,_Piment rouge, graines de carambole, sucre,_Arômes Identiques Nature, Acide Citrique _(E330), Maltrodextrine & Dextrose.',
        '',
        'assets/images/products/snacks/nutrition/nutrition3.png'),
    ProductDetail(
        4,
        44,
        'Refreshing Minty chocolate Pan Masala. A blend of chocolate covered Fennel, Coconut, Sesame Seeds and Betel Nuts.',
        'Corn Meal, Yellow Peas, Vegetable Oil (Palmolein), _Salt, Red Chilli, Citric Acid_(E330) and Nature Identical Flavor',
        'semoule de maïs, pois jaunes, Huile Végétale _(Palmoléine), sel, piment rouge, acide citrique _(E330) et Nature Saveur identique',
        '',
        'assets/images/products/snacks/nutrition/nutrition4.png'),
    ProductDetail(
        5,
        45,
        'Popstar Champ is made from 100% corn that is baked not fried. Champ has a melt-in-your-mouth soft texture with a yummy Cheese flavour.',
        'Corn Meal, Vegetable Oil (Palmolein), Salt, Whey_Powder, Maltodextrin, Garlic Powder, Onion Powder, _Dextrose, Permitted Food Color Sunset Yellow (E110) _and Nature Identical Flavor (Cheese).',
        'Farine de maïs, huile végétale (palmoléine), sel, poudre _de lactosérum, maltodextrine, poudre d\'ail, poudre _d\'oignon, dextrose, colorant alimentaire autorisé jaune _orangé (E110) et arôme identique à la nature (fromage).',
        '',
        'assets/images/products/snacks/nutrition/nutrition5.png'),
    ProductDetail(
        6,
        46,
        'Refreshing Minty chocolate Pan Masala. A blend of chocolate covered Fennel, Coconut, Sesame Seeds and Betel Nuts.',
        'Potato Powder, Potato Starch, Rice Flour, Vegetable Oil, _Salt, Maltodextrin, Acidity Regulator (Citric Acid E330), _Red Chilli, Black Pepper, Ginger Powder, Cumin, _Coriander Powder, Nature Identical Flavour  & Vitamins _(A,C & D) ',
        'Poudre de pomme de terre, fécule de pomme de terre, _farine de riz, Huile Végétale, Sel, Maltodextrine, Régulateur _d\'acidité (Acide Citrique E330), Piment rouge, poivre noir, _poudre de gingembre, Cumin, poudre de coriandre, nature _identique Saveur & Vitamines (A,C & D)',
        '',
        'assets/images/products/snacks/nutrition/nutrition6.png'),
    ProductDetail(
        7,
        47,
        'A fried potato pallet snack made from high quality potato based pellets. Fry-O is sure to satisfy your craving for something savory. Fry-O is available in Sweet n’ Sour and Veggi Dip.',
        'Potato Powder, Potato Starch, Rice Flour, Vegetable Oil, _Salt, Sugar, Whey Powder, Dextrose, Nature Identical _Flavour, Maltodextrin, Citric Acid (E-330) & Vitamins (A,C _& D).',
        'Poudre de pomme de terre, fécule de pomme de terre, _farine de riz, Huile végétale, sel, sucre, lactosérum en _poudre, Dextrose, arôme identique à la nature, _maltodextrine, Acide citrique (E-330) et vitamines (A, C _et D).',
        '',
        'assets/images/products/snacks/nutrition/nutrition7.png'),
    ProductDetail(
        8,
        48,
        'A fried potato pallet snack made from high quality potato based pellets. Fry-O is sure to satisfy your craving for something savory. Fry-O is available in Sweet n’ Sour and Veggi Dip.',
        'Potato Powder, Potato Starch, Rice Flour, Vegetable Oil, _Salt, Maltodextrin, Acidity Regulator (Sodium Citrate _E331), Nature Identical Flavour & Vitamins (A,C & D) ',
        'Poudre de pomme de terre, fécule de pomme de terre, _farine de riz, Huile Végétale, Sel, Maltodextrine, _Régulateur d\'acidité (citrate de sodium E331), Saveur et _vitamines identiques à la nature (A, C et D)',
        '',
        'assets/images/products/snacks/nutrition/nutrition8.png'),
    ProductDetail(
        9,
        49,
        'Refreshing Minty chocolate Pan Masala. A blend of chocolate covered Fennel, Coconut, Sesame Seeds and Betel Nuts.',
        'Corn Meal, Vegetable Oil (Palmolein),Sugar, Maltodextrin, Salt, _Black Pepper, Ginger, Onion, Malic Acid (E-296), Ponceau 4R _(E-124), NN Sweetener (Aspartame), Nature Identical Flavour _Jalapeno ',
        'semoule de maïs, huile végétale (palmoléine), Sucre, _maltodextrine, sel, poivre noir, Gingembre, Oignon, _Acide Malique (E-296), Ponceau 4R (E-124), Édulcorant _NN (Aspartame), Saveur identique à la nature Jalapeno',
        '',
        'assets/images/products/snacks/nutrition/nutrition9.png'),
    ProductDetail(
        10,
        50,
        'Refreshing Minty chocolate Pan Masala. A blend of chocolate covered Fennel, Coconut, Sesame Seeds and Betel Nuts.',
        'Corn Grits, Corn Starch, Rice, Vegetable Oil (Palmolein), Salt, _Red Chilli, Sugar, Cumin, Coriander, Black Pepper, Mango _Powder, Citric Acid (E-330), Food Colors Tartrazine Yellow _(E-102) & Sunset Yellow (E-110), Trisodium Citrate (E-331) & _Yeast Extract.',
        'Gruau de maïs, amidon de maïs, riz, huile végétale _(palmoléine), sel, piment rouge, sucre, cumin, coriandre, _poivre noir, poudre de mangue, acide citrique (E-330), _colorants alimentaires tartrazine jaune (E-102) et _coucher de soleil Jaune (E-110), citrate trisodique _(E-331) et extrait de levure.',
        '',
        'assets/images/products/snacks/nutrition/nutrition10.png'),
    ProductDetail(
        11,
        51,
        'Refreshing Minty chocolate Pan Masala. A blend of chocolate covered Fennel, Coconut, Sesame Seeds and Betel Nuts.',
        'Corn Meal, Vegetable Oil (Palmolein), Salt, Whey Powder, _Maltodextrin, Garlic Powder, Onion Powder, Dextrose, _Permitted Food Color Sunset Yellow (E110) and Nature _Identical Flavor (Cheese).',
        'Farine de maïs, huile végétale (palmoléine), sel, poudre _de lactosérum, maltodextrine, poudre d\'ail, poudre _d\'oignon, dextrose, colorant alimentaire autorisé jaune _orangé (E110) et arôme identique à la nature (fromage).',
        '',
        'assets/images/products/shahi_nimco/nutrition/nutrition11.png'),
    ProductDetail(
        12,
        52,
        'A 100% wheat snack with taste of real chicken. A delicious snack for an extra burst of energy and flavour.',
        'Wheat Flour, Vegetable Oil (Palmolein), Salt, Sugar, _Black Pepper, Red Chilli, Black salt, Sodium _Bicarbonate (E-500), Dextrose, Maltodextrin, Citric _Acid (E-330) & Nature Identical Flavor (Chicken _Powder)',
        'Farine de blé, huile végétale (palmoléine), sel, sucre, _poivre noir, piment rouge, sel noir, bicarbonate de _sodium (E-500), dextrose, maltodextrine, acide citrique _(E-330) et arôme identique à la nature (poudre de _poulet)',
        '',
        'assets/images/products/snacks/nutrition/nutrition12.png'),
    ProductDetail(
        13,
        53,
        'A 100% wheat snack with taste of real chicken. A delicious snack for an extra burst of energy and flavour.',
        'Wheat Flour, Vegetable Oil (Palmolein), Salt, Black _Salt, Black Pepper, Garlic Powder, Sugar, Red Chilli, _Mango Powder, Citric Acid (E-330) & Nature Identical _Flavor.',
        'Farine de blé, huile végétale (palmoléine), sel, sel noir, _poivre noir, poudre d\'ail, sucre, piment rouge, poudre _de mangue, acide citrique (E-330) et arôme identique _à la nature.',
        '',
        'assets/images/products/snacks/nutrition/nutrition13.png'),
    ProductDetail(
        14,
        54,
        'An extruded snack made from 100% corn that is baked rather than fried. Popstar is the healthier alternative to fried potato snacks. Available in 3 mouthwatering flavours, Achari Chaska, Chatpata Chicken and Cheesy Cheese.',
        'Corn Grits, Salt, Vegetable Oil (Palmolein), _Maltodextrin, Dextrose, Whey Powder, Onion _Powder, Garlic Powder, Sunset Yellow (E-110) & _Nature Identical Flavour (Cheese)',
        'Gruau de maïs, sel, huile végétale (palmoléine), _Maltodextrine, dextrose, poudre de lactosérum, poudre _d\'oignon, poudre d\'ail, jaune orangé (E-110) et saveur _identique à la nature (fromage)',
        '',
        'assets/images/products/snacks/nutrition/nutrition14.png'),
    ProductDetail(
        15,
        55,
        'An extruded snack made from 100% corn that is baked rather than fried. Popstar is the healthier alternative to fried potato snacks. Available in 3 mouthwatering flavours, Achari Chaska, Chatpata Chicken and Cheesy Cheese.',
        'Corn Meal, Vegetable Oil (Palmolein), Salt, Garlic _Powder, Black Pepper, Red Chilli, Maltodextrin and _Nature Identical Flavor,',
        'Farine de Maïs, Huile Végétale (Palmoléine), Sel, _Poudre d\'Ail, Poivre Noir, Piment Rouge, Maltodextrine _et Arôme Identique Nature,',
        '',
        'assets/images/products/snacks/nutrition/nutrition15.png'),
    ProductDetail(
        16,
        56,
        'An extruded snack made from 100% corn that is baked rather than fried. Popstar is the healthier alternative to fried potato snacks. Available in 3 mouthwatering flavours, Achari Chaska, Chatpata Chicken and Cheesy Cheese.',
        'Corn Grits, Vegetable Oil (Palmolein), Salt, _Red Chili, Citric Acid (E-330) & Nature _Identical Flavor. ',
        'Gruau de maïs, huile végétale (palmoléine), _Sel, piment rouge, acide citrique (E-330) et _Saveur identique à la nature.',
        '',
        'assets/images/products/snacks/nutrition/nutrition16.png'),
    ProductDetail(
        17,
        57,
        'An extruded snack made from 100% corn that is baked rather than fried. Popstar is the healthier alternative to fried potato snacks. Available in 3 mouthwatering flavours, Achari Chaska, Chatpata Chicken and Cheesy Cheese.',
        'Corn Meal, Vegetable Oil (Palmolein), Salt, Red Chili, _Citric Acid (E330), Dextrose, Maltodextrin, Onion _Powder, Whey Powder, Garlic Powder, Sugar & Nature _Identical Flavor.',
        'semoule de maïs, huile végétale (palmoléine), Sel, _piment rouge, acide citrique (E330), Dextrose, _maltodextrine, poudre d\'oignon, Poudre de lactosérum, _poudre d\'ail, sucre & Saveur identique à la nature.',
        '',
        'assets/images/products/snacks/nutrition/nutrition17.png'),
  ];

  static final List<ProductDetail> mouthFreshenerDetail = [
    ProductDetail(
        1,
        61,
        '----------------------------------',
        '----------------------------------',
        '----------------------------------',
        'assets/images/products/mouth_freshener/arabic/arabic1.png',
        'assets/images/products/mouth_freshener/nutrition/nutrition1.png'),
    ProductDetail(
        2,
        62,
        '----------------------------------',
        '----------------------------------',
        '----------------------------------',
        'assets/images/products/mouth_freshener/arabic/arabic2.png',
        'assets/images/products/mouth_freshener/nutrition/nutrition2.png'),
    ProductDetail(
        3,
        63,
        '----------------------------------',
        '----------------------------------',
        '----------------------------------',
        'assets/images/products/mouth_freshener/arabic/arabic3.png',
        '' /*'assets/images/products/mouth_freshener/nutrition/nutrition3.png'*/),
    ProductDetail(
        4,
        64,
        '----------------------------------',
        '----------------------------------',
        '----------------------------------',
        'assets/images/products/mouth_freshener/arabic/arabic4.png',
        'assets/images/products/mouth_freshener/nutrition/nutrition4.png'),
    ProductDetail(
        5,
        65,
        '----------------------------------',
        '----------------------------------',
        '----------------------------------',
        'assets/images/products/mouth_freshener/arabic/arabic5.png',
        'assets/images/products/mouth_freshener/nutrition/nutrition5.png'),
    ProductDetail(
      6,
      66,
      '----------------------------------',
      '----------------------------------',
      '----------------------------------',
      'assets/images/products/mouth_freshener/arabic/arabic6.png',
      '', /*'assets/images/products/mouth_freshener/nutrition/nutrition6.png'*/
    ),
    ProductDetail(
      7,
      67,
      '----------------------------------',
      '----------------------------------',
      '----------------------------------',
      'assets/images/products/mouth_freshener/arabic/arabic7.png',
      '', /*'assets/images/products/mouth_freshener/nutrition/nutrition7.png'*/
    ),
    ProductDetail(
        8,
        68,
        '----------------------------------',
        '----------------------------------',
        '----------------------------------',
        'assets/images/products/mouth_freshener/arabic/arabic8.png',
        'assets/images/products/mouth_freshener/nutrition/nutrition8.png'),
    ProductDetail(
        9,
        69,
        '----------------------------------',
        '----------------------------------',
        '----------------------------------',
        'assets/images/products/mouth_freshener/arabic/arabic9.png',
        'assets/images/products/mouth_freshener/nutrition/nutrition9.png'),
    ProductDetail(
        10,
        70,
        '----------------------------------',
        '----------------------------------',
        '----------------------------------',
        'assets/images/products/mouth_freshener/arabic/arabic10.png',
        'assets/images/products/mouth_freshener/nutrition/nutrition10.png'),
    ProductDetail(
      11,
      71,
      '----------------------------------',
      '----------------------------------',
      '----------------------------------',
      'assets/images/products/mouth_freshener/arabic/arabic11.png',
      '', /*'assets/images/products/mouth_freshener/nutrition/nutrition11.png'*/
    ),
    ProductDetail(
        12,
        72,
        '----------------------------------',
        '----------------------------------',
        '----------------------------------',
        'assets/images/products/mouth_freshener/arabic/arabic12.png',
        'assets/images/products/mouth_freshener/nutrition/nutrition12.png'),
  ];

// static final List<ProductDetail> snacksDetails = [
//   ProductDetail(
//       1,
//       31,
//       'A fried potato pallet snack made from high quality potato based pellets. Fry-O is sure to satisfy your craving for something savory. Fry-O is available in Sweet n’ Sour and Veggi Dip.',
//       'Potato Powder, Potato Starch, Vegetable Oil, Salt, Sugar, Seasoning, Citric Acid (E-330), Flavour Enhancer (E-621)',
//       'assets/images/nutrition_facts/fry_o_sns_nf.jpg'),
//   ProductDetail(
//       2,
//       32,
//       'A fried potato pallet snack made from high quality potato based pellets. Fry-O is sure to satisfy your craving for something savory. Fry-O is available in Sweet n’ Sour and Veggi Dip.',
//       'Potato Powder, Potato Starch, Vegetable Oil, Salt, Sugar, Seasoning, Citric Acid (E-330), Flavour Enhancer (E-621)',
//       'assets/images/nutrition_facts/fry_o_vd_nf.jpg'),
//   ProductDetail(
//       3,
//       33,
//       'Crispy Corn Sticks covered with a copious amount of flavours. Available in Spicy Masala and Cheese. Kin Korn is sure to satisfy your hunger.',
//       'Corn Grits, Vegetable Oil, Natural Flavours, Salt, Food Colour Sunset Yellow (E-110)',
//       'assets/images/nutrition_facts/kinkorn_cheese_nf.jpg'),
//   ProductDetail(
//       4,
//       34,
//       'Crispy Corn Sticks covered with a copious amount of flavours. Available in Spicy Masala and Cheese. Kin Korn is sure to satisfy your hunger.',
//       'Corn Grits, Vegetable Oil, Natural Flavours, Spices, Salt, Food Colour (E-129)',
//       'assets/images/nutrition_facts/kinkorn_spicy_nf.jpg'),
//   ProductDetail(
//       5,
//       35,
//       'An extruded snack made from 100% corn that is baked rather than fried. Popstar is the healthier alternative to fried potato snacks. Available in 3 mouthwatering flavours, Achari Chaska, Chatpata Chicken and Cheesy Cheese.',
//       'Corn Meal, Salt, Vegetable Oil, Natural Flavors, Spices',
//       'assets/images/nutrition_facts/pop_star_ac_nf.jpg'),
//   ProductDetail(
//       6,
//       36,
//       'Popstar Champ is made from 100% corn that is baked not fried. Champ has a melt-in-your-mouth soft texture with a yummy Cheese flavour.',
//       'Corn Meal, Salt, Vegetable Oil, Natural Flavors, Spices',
//       'assets/images/nutrition_facts/pop_star_champ_nf.jpg'),
//   ProductDetail(
//       7,
//       37,
//       'An extruded snack made from 100% corn that is baked rather than fried. Popstar is the healthier alternative to fried potato snacks. Available in 3 mouthwatering flavours, Achari Chaska, Chatpata Chicken and Cheesy Cheese.',
//       'Corn Meal, Salt, Vegetable Oil, Natural Flavors, Spices',
//       'assets/images/nutrition_facts/pop_star_chicken_chatpata_nf.jpg'),
//   ProductDetail(
//       8,
//       38,
//       'An extruded snack made from 100% corn that is baked rather than fried. Popstar is the healthier alternative to fried potato snacks. Available in 3 mouthwatering flavours, Achari Chaska, Chatpata Chicken and Cheesy Cheese.',
//       'Corn Meal, Salt, Vegetable Oil, Natural Flavors, Spices',
//       'assets/images/nutrition_facts/pop_star_cheesy_cheese_nf.jpg'),
//   ProductDetail(
//       9,
//       39,
//       'A 100% wheat snack with taste of real chicken. A delicious snack for an extra burst of energy and flavour.',
//       'Wheat Flour, Vegetable Oil, Salt, Spices, Citric Acid (E-330), Flavour Enhancer (E-621)',
//       'assets/images/nutrition_facts/wheat_o_chips_nf.jpg'),
//   ProductDetail(
//       10,
//       40,
//       'A 100% wheat snack with taste of real chicken. A delicious snack for an extra burst of energy and flavour.',
//       'Wheat Flour, Vegetable Oil, Salt, Spices, Citric Acid (E-330), Flavour Enhancer (E-621)',
//       'assets/images/nutrition_facts/wheat_o_karariyan_nf.jpg'),
//   ProductDetail(
//       11,
//       41,
//       'A 100% wheat snack with taste of real chicken. A delicious snack for an extra burst of energy and flavour.',
//       'Wheat Flour, Vegetable Oil, Salt, Seasoning, Citric Acid (E-330), Flavour Enhancer (E-621)',
//       'assets/images/nutrition_facts/wheat_o_original_nf.jpg'),
// ];
//
// static final List<ProductDetail> frozenFoodsDetail = [
//   ProductDetail(
//       1,
//       51,
//       'Shahi Paratha’s are part of the newest venture of Shahi foods. Shahi uses the finest quality ingredients to gives its customer the authentic homemade flavours and feels.',
//       'Wheat Flour, Margarine, Salt, Leavening Agent, Water, Milk',
//       'assets/images/nutrition_facts/shahi_paratha_fm_nf.jpg'),
//   ProductDetail(
//       2,
//       52,
//       'Shahi Paratha’s are part of the newest venture of Shahi foods. Shahi uses the finest quality ingredients to gives its customer the authentic homemade flavours and feels.',
//       'Wheat Flour, Margarine, Salt, Leavening Agent, Water, Milk',
//       'assets/images/nutrition_facts/shahi_paratha_jp_nf.jpg'),
//   ProductDetail(
//       3,
//       53,
//       'Shahi Paratha’s are part of the newest venture of Shahi foods. Shahi uses the finest quality ingredients to gives its customer the authentic homemade flavours and feels.',
//       'Wheat Flour, Margarine, Salt, Leavening Agent, Water, Milk',
//       'assets/images/nutrition_facts/shahi_plain_paratha_nf.jpg'),
// ];

}
